"""Trace brand/wrynch-logo-source.png into vector paths (run: python3 brand/trace.py).
Writes brand/wrynch-wordmark.svg, brand/wrynch-mark.svg and src/ui/logoPaths.ts."""
import cv2, numpy as np, json
from PIL import Image

src = Image.open('brand/wrynch-logo-source.png').convert('RGBA')
a = np.asarray(src).astype(np.float32)
lum = 0.299 * a[..., 0] + 0.587 * a[..., 1] + 0.114 * a[..., 2]
ink = ((lum < 128) & (a[..., 3] > 128)).astype(np.uint8) * 255   # black shapes on white/transparent

# Trace at 2x for smoother curves.
S = 2
big = cv2.resize(ink, None, fx=S, fy=S, interpolation=cv2.INTER_CUBIC)
big = cv2.GaussianBlur(big, (5, 5), 0)
_, big = cv2.threshold(big, 127, 255, cv2.THRESH_BINARY)
contours, hier = cv2.findContours(big, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)

def path_of(cs):
    out = []
    for c in cs:
        c = cv2.approxPolyDP(c, 1.2, True).reshape(-1, 2) / S
        if len(c) < 3: continue
        out.append('M' + 'L'.join(f'{x:.1f} {y:.1f}'.replace('.0 ', ' ').replace('.0', '') if False else f'{round(x,1):g} {round(y,1):g}' for x, y in c) + 'Z')
    return ''.join(out)

ys, xs = np.nonzero(ink)
x0, y0, x1, y1 = xs.min(), ys.min(), xs.max() + 1, ys.max() + 1

# Group outer contours with their holes; find the wrench (the shape that reaches the top of the logo).
groups = []
for i, c in enumerate(contours):
    if hier[0][i][3] != -1: continue
    kids = [contours[j] for j in range(len(contours)) if hier[0][j][3] == i]
    x, y, w, h = cv2.boundingRect(c)
    if w * h < 400: continue
    groups.append({'cs': [c] + kids, 'box': (x / S, y / S, (x + w) / S, (y + h) / S)})
head = min(groups, key=lambda g: g['box'][1])
# The wrench is every shape whose centre lies within the jaw's width (jaw, adjuster, handle).
parts = [g for g in groups if head['box'][0] <= (g['box'][0] + g['box'][2]) / 2 <= head['box'][2]]
wrench = {'cs': [c for g in parts for c in g['cs']],
          'box': (min(g['box'][0] for g in parts), min(g['box'][1] for g in parts), max(g['box'][2] for g in parts), max(g['box'][3] for g in parts))}

def shift(cs, dx, dy):
    return [c - np.array([[dx * S, dy * S]], dtype=c.dtype) for c in cs]

word_d = path_of(shift([c for g in groups for c in g['cs']], x0, y0))
wx0, wy0, wx1, wy1 = wrench['box']
mark_d = path_of(shift(wrench['cs'], wx0, wy0))
W, H = x1 - x0, y1 - y0
MW, MH = round(wx1 - wx0, 1), round(wy1 - wy0, 1)

open('brand/wrynch-wordmark.svg', 'w').write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}"><path fill="#15171A" fill-rule="evenodd" d="{word_d}"/></svg>\n')
open('brand/wrynch-mark.svg', 'w').write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {MW:g} {MH:g}"><path fill="#15171A" fill-rule="evenodd" d="{mark_d}"/></svg>\n')
open('src/ui/logoPaths.ts', 'w').write(
    '// Generated by brand/trace.py from brand/wrynch-logo-source.png. Do not edit by hand.\n'
    f'export const WORDMARK = {{ w: {W}, h: {H}, d: {json.dumps(word_d)} }};\n'
    f'export const MARK = {{ w: {MW:g}, h: {MH:g}, d: {json.dumps(mark_d)} }};\n')
print('wordmark', W, H, len(word_d), 'bytes; mark', MW, MH, len(mark_d), 'bytes; shapes', len(groups))
